server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc?server?Timezone=GMT%2B8
    data-username: root
    data-password: rootadmin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
